import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import NavFooterWrapper from "@/components/HOC/NavFooterWrapper";
import { Montserrat, Red_Hat_Display } from 'next/font/google'
import { Analytics } from "@vercel/analytics/react"

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat',
  display: 'swap',
})

const redHatDisplay = Red_Hat_Display({
  subsets: ['latin'],
  variable: '--font-red-hat-display',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressContentEditableWarning suppressHydrationWarning>
      <body
        className={cn("antialiased dark", montserrat.variable, redHatDisplay.variable)}
      >
        <NavFooterWrapper>
            {children}
        </NavFooterWrapper>
        <Analytics/>
      </body>
    </html>
  );
}
